sudo: false
language: java
jdk:
- oraclejdk8
addons:
  sauce_connect: true
env:
  global:
  - NODE_VERSION=6
  - secure: KGfm7fTDAPiOhjcycDUMIp311EIWb8jHirTjKWqHWDoTU7A+4KoFM+PwIRV3WpNQaZ2NJkRiWBiPtOPhp1q0snU3Hza/NhUd8vOOOMbT7xGs67AOuAHUZzm1SyinzKLNQ4c1SDuCo7nIA962+pDrBf7hBiDRC0BkYKxPnZ82chvS6weWbsN9D8tI1769v6TRRLWWioqj4ojjsRNO1myVQ5sVzYEMcLypOri66wfuQKv0uCUgitff1uSefGP8TLmx/mAriADtB8pZLrBzrHrdNtnCfdSY4LBxJcuRQCdXCBjmQggj0P5cEFb/wf5tVjPuVWeE3IJXMw0s41A8i0hTCntIOzy6BQZA4NxWNNCfBB43oPnJxt60vrbJSgJOuxr0PXL8GF7WyQEBvLDjyz5+4tJQAsSfo4M6jHIbQb+HVhL4gxBdtMJzWxahXpCyDqnueijfHMGSMu9mq0kA/KTh7CgRqYgSnE9JYCQqOuWBSqGjjKMTK+tLEuhQX9ZP5SpYlWNeWWII32EIWZJl7iypo5qvd/AjAI5s/VDSDblgmSXdqYqQSu94SbChYCrBJ/pnv8JMYPjv4nFsJGY5EKA5acFc+zp4onunKFbCs+BgvsVJolWb2ph24/aBLnOCUJ8MTgm4saVwAourSg/tAkGN0MnQ8MmiP7GyhGykLxWPqrM=
  - secure: M/p4pkAIfFMIkMwUP2iZbh0v9xKss4UBnIEKh0wqYYk4ox0uBLr0WIcJi/+ufnhw4h4EXV4iosJoybhMdZSKoj5QfVSxNtGHoWoHArC9tuS4159EN1Ng/wrJWR/ZGfOdvBD4fLP7QkrQHz9h6s1+m+TfQs+vI97Ks/YjUiDv5H+w+rc48dgO2xBUihZ69fh0w3ivi/86zj8rMAwpfTl4IaGQTXYEiDHiq7lbRnXwSZLa2/rvCUGv4CdMt/exDcDoTVLMX6c5IM8OBv+OWaAyp8yoTjowOLRJfV2RcFISGmigCyaaRbLkXn6h4d+x1ToqaOS7ll2zcda347jfQ5ezePa+mScrc+on16Q9Nwl0qXq5dFv9t5tRDwt80cJzGpGpEL4aWIDldwYO/wX57FhzN7spM7VTnvc+SWkTLmdhagX+hdlX+t9ltnM/tF+rVCnLqzyDvv/I+TIfsoBjNSAIRS8UB/PYcNORb1h8nCqdV+DkjewdjztX+wofKIJ4fuKGBUiSg9KgjikIU5kyI8lj246D5zUKJkQ0EHy73ejubxQ/ZdrkVuSlVtZb94oBdhRwGzbs7lVS7DQ+AVDsCohFkLWffEOjPswmx8CR5KBCGBMdr3LaxsYBkOKbjK92PvGj4yyFBdn0WSx7y67jpesV9KzOtAkjm52Tl2S/hejoqWc=
install:
- nvm install $NODE_VERSION
- npm install
script:
- npm run build
- npm run test
