sudo: false
language: java
jdk:
  - oraclejdk8
addons:
  sauce_connect: true
env:
  matrix:
    - NODE_VERSION=6
  global:
    - secure: IKCJMGKtNmScqLAr2YG32FJKvMLFyOkMw8RccUb1MHJFfJ/muEeAj57gkFNV74ykpAzdztUzVBOoZbfUYTXRYxwEO+dZ2Hv5yhz2DNBZXRpk+cUXi/AFXrSo94oUCOS/cw6B+VQWZW9txZUF1zE+UIwygLWO1bTjQKHqmd3Q00Fmm8H0me+BF3V9KTCk2lyppv58vJoYmZdj9pHfGowvZr7vup2u7JE8fHiQq8ZKFXepV3D36LRjtdBPAe9WkW8ccijl5njzzpF8sqybjECXxw96nHBT6PCjDiKjq+XOib1ZKO9LvfUl5A6j5k9ebaLgXl/F2sjNp+s4a834YOna+wkUSTwlCOltJ29h9l3IYmbcDOMY9uFi8FrNm+iDYuNF1njTdReCkZAR6NvHBf5dyRjGZQ4h8DH/hcui2bE+5FJVCs2ZXqDunipTyU11k7J87i7oPq/mrf1G5oN+WDPj9ROcsyaG4lrwdzQC4Ojq6vuIXiyhPbqqP/JyXxp8TEZgr0qTU3GyIvv33oONmu/329bJCl2GmTQ5ppVomj8mxkBgXfK9Uy7dX4CXRy3FxLAz+V43qIaP44YJBQ0xFE/RqvoZBkRAg+z0+bKa3m65jM3HnwNgxG7ODEo9BMnSve8HwGlAgBiHid4w7WQOTXgEZKI64Sk8MVOEkHqYi8fmQvo=
    - secure: TkUcpUtaQC/b7zjIxfOLiXd+ZbwkhjFybhJThqsf9qcfVdy/Q2u9jriMJWtW0iT9P3K6LNltnLENBW3DzRie7XOVq6uU6swrQYLD948HJnvecDYMmWtW4Ghx90k/Y6kDGbIu3Juyc08Knt9U/T20WwwIL9nUNMuMEtlQfLMtJb3z2mLiQxlIY52cKuRb6a+lQn1OZ/c1L+xClSB6VVK/uWykL1If7Qr1vQav8Tlcssm0SRBQd4Akn6IDdpS0IlXFj3ns70xTXd0/KInQKg3kdximKEbHaZbjBSEZr77aMjD9mq442Xdes5Aa8pDFstISP+guq64wSRSeSs61usce1SqRgb5qxVSS7AEQFWntv4Gq8je2ebT4J9pHlxCc4hLoKuyVDiX9AYkeH76XR8jFFePdw35IELA2FNCxPTd6U6y9AoL1/TkuFu561dTNWEuLKvds+iQTfVxKbPN3bJd5wMVYtEelXyM2ILxAPXoEMnwBGufzyFmynIOV6wSNfYnBpGMkFHmgSsskQS5nvWDOXcA8kqxPgXu0WDpw0FRrUjmQiMv14psAErJEd1L8RzT46LFtC7i3vuk0S4YqwHFaC6w2kWeK3HSp4IbvVZzGktqBfgc0jeAnSmSlBehq6iwEqel7GLKzmXfMaIzpLr4bO5lLPubdw5IDf5EHqIbAki4=
install:
  - nvm install $NODE_VERSION
  - npm install
script:
  - npm run build
  - npm run test
